version: '1.0'
services:
    service_sql2022:
        build: 
          context: .
          dockerfile: dockerfile_sql2022
          args:
            buildno: 1
        image: image_sql2022
        ports:  
          - "1433:1433"
        container_name: container_sql2022
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: c/docker/volumes_local/sqlbackup
  