# ------------------------------------------------------------------------------------------------------------------------------------------
# download image ubuntu
FROM ubuntu:20.04
# ------------------------------------------------------------------------------------------------------------------------------------------
# installing sudo
RUN apt-get update
RUN apt-get install -y sudo
# ------------------------------------------------------------------------------------------------------------------------------------------
# create the mssql user
RUN useradd -u 10001 mssql
#RUN useradd mssql sudo
# ------------------------------------------------------------------------------------------------------------------------------------------
# installing SQL Server
RUN apt-get update
RUN apt-get install -y wget software-properties-common apt-transport-https
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2022.list)"
RUN apt-get update 
RUN apt-get install -y mssql-server

RUN apt-get install -y sudo

RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
# ------------------------------------------------------------------------------------------------------------------------------------------
# creating directories
RUN mkdir /var/opt/sqlserver
RUN mkdir /var/opt/sqlserver/data
RUN mkdir /var/opt/sqlserver/log
RUN mkdir /var/opt/sqlserver/backup
# ------------------------------------------------------------------------------------------------------------------------------------------
# set permissions on directories
RUN chown -R mssql:mssql /var/opt/sqlserver
RUN chown -R mssql:mssql /var/opt/mssql
# ------------------------------------------------------------------------------------------------------------------------------------------
# switching to the mssql user
USER mssql
# ------------------------------------------------------------------------------------------------------------------------------------------
# starting SQL Server
CMD /opt/mssql/bin/sqlservr
# ------------------------------------------------------------------------------------------------------------------------------------------
